# Generated by Django 4.0.3 on 2022-04-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomerPosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerPosts.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Myalert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Remaind_me', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worksubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Description', models.TextField()),
                ('Allocated_on', models.DateTimeField(auto_now_add=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerDetails.details')),
            ],
        ),
    ]
