# Generated by Django 4.0.3 on 2022-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassigment',
            name='Completed',
            field=models.BooleanField(default=True),
        ),
    ]
