# Generated by Django 4.0.3 on 2022-05-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDetails', '0002_userassigment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassigment',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
