# Generated by Django 4.0.3 on 2022-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDetails', '0003_alter_userassigment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminassigment',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
