# Generated by Django 4.0.3 on 2022-05-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDetails', '0004_adminassigment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassigment',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
