# Generated by Django 4.0.3 on 2022-05-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDetails', '0006_alter_userassigment_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminassigment',
            old_name='Completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='adminassigment',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='adminassigment',
            old_name='Metting_description',
            new_name='metting_description',
        ),
        migrations.RenameField(
            model_name='adminassigment',
            old_name='Metting_scheldule',
            new_name='metting_scheldule',
        ),
        migrations.RenameField(
            model_name='adminassigment',
            old_name='Work_Description',
            new_name='work_Description',
        ),
        migrations.RenameField(
            model_name='userassigment',
            old_name='Completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='userassigment',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='userassigment',
            old_name='Metting_description',
            new_name='metting_description',
        ),
        migrations.RenameField(
            model_name='userassigment',
            old_name='Work_Description',
            new_name='work_Description',
        ),
    ]
