# Generated by Django 4.0.3 on 2022-05-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerDetails', '0007_rename_completed_adminassigment_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassigment',
            old_name='Metting_scheldule',
            new_name='metting_scheldule',
        ),
    ]
