# Generated by Django 4.0.3 on 2022-04-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='post',
            new_name='name',
        ),
    ]
